site_name: DDS Manual
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to Light Mode
      primary: green
      accent: white 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark Mode
      primary: green
      accent: white

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jHXTdNjYCg 

nav:
  - Home: index.md
  - Beginner Guide:
    - Onshape Intro: onshape-intro.md
    - Starter Projects: starter-projects.md
  - Resources:
    - CAD Examples: cad-examples.md