site_name: FRCDesign.org
repo_url: https://github.com/davidsdesignserver/dds-manual
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to Light Mode
      primary: green
      accent: white
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark Mode
      primary: green
      accent: black
  icon:
    logo: fontawesome/solid/book-open
  
  favicon: img/favicon.png

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jHXTdNjYCg 
  analytics:
    provider: google
    property: G-KX3MNPJ4L6

nav:
  - Home: index.md
  - Design Guide:
    - design-guide/index.md
    - Beginner Stages:
      - Stage 0: 
        - "A: Introduction to CAD": design-guide/stage0/0A-introductionToCAD.md
        - "B: Onshape Setup": design-guide/stage0/0B-setup.md
        - "C: Navigating Onshape": design-guide/stage0/0C-navigation.md
        - "D: Theory": design-guide/stage0/0D-theory.md
      - Stage 1:
        - "A: Onshape Fundamentals": design-guide/stage1/1A-onshapeFundamentals.md
        - "B: Swerve Drivebase": design-guide/stage1/1B-swerveDrivebase.md
        - "C: Gearbox Projects": design-guide/stage1/1C-gearboxes.md
      - Stage 2:
        - "A: Full Detail Drivebase": design-guide/stage2/2A-drivebaseFullDetail.md
        - "B: Basic Shooter": design-guide/stage2/2B-basicShooter.md
        - "C: Deadaxle Pivot": design-guide/stage2/2C-deadaxlePivot.md
        - "D: 2023 UTB Intake": design-guide/stage2/2D-2023utbIntake.md
        - "E: 2023 Pasta Roller Intake": design-guide/stage2/2E-2023pastaRollerIntake.md
        - "F: Four-bar Linkage": design-guide/stage2/2F-fourbarLinkage.md
        - "G: Cascade Elevator": design-guide/stage2/2G-cascadeElevator.md
      - Stage 3: 
        - "A: Multidoc & Mastersketching": design-guide/stage3/3A-multidoc&MS.md
        - "B: 973 2020 Robot": design-guide/stage3/3B-973-2020.md
        - "C: 973 2023 Robot": design-guide/stage3/3C-973-2023.md
    - Intermediate Stages: design-guide/stage4/4.md
  
  - Design Challenges:
    - design-challenge/index.md
    - Week 1 | Swerve Drivebase: design-challenge/challenges/week1.md

  - Design Fundamentals:
    - design-fundamentals/index.md
    - Mechanisms:
      - Drivetrain: design-fundamentals/mechanisms/drivebase.md

  - Best Practices:
      - design-standards/index.md
      - Document Setup: design-standards/document-setup.md
      - Sub-Document Setup: design-standards/sub-document-setup.md
      - Master Sketch Best Practices: design-standards/mastersketch-setup.md
      - Feature Tree Best Practices: design-standards/feature-tree-setup.md
      - Assembly Best Practices: design-standards/assembly-setup.md
      - Hardware Design Standards: design-standards/hardware-design-standards.md

  - Resources:
    - resources/index.md
    - Glossary: resources/glossary.md
    - Mechanism Examples:
      - mechanism-examples/index.md
      - Slapdown Intakes:
        - mechanism-examples/intake/slapdown/index.md
        - 4414 Style  Intake: mechanism-examples/intake/slapdown/examples/4414style.md
        - Washed Beavertail Intake: mechanism-examples/intake/slapdown/examples/washed.md
        - Low Pivot Slapdown Intake: mechanism-examples/intake/slapdown/examples/low.md
        - 6423 Crescendo Slapdown Intake: mechanism-examples/intake/slapdown/examples/6423otb.md
      - 4 Bar Intakes:
        - mechanism-examples/intake/4bar/index.md
        - 1678's 2022 Intake: mechanism-examples/intake/4bar/examples/1678.md
        - Andrew's Clean 4 Bar Intake: mechanism-examples/intake/4bar/examples/clean.md
        - Vaughn's 4 Bar Intake: mechanism-examples/intake/4bar/examples/vaughn4bar.md
      - Cascade Elevators:
        - mechanism-examples/elevator/cascade/index.md
        - 2 Stage Cascade Elevator: mechanism-examples/elevator/cascade/examples/2stage.md
        - 3 Stage Cascade Elevator: mechanism-examples/elevator/cascade/examples/3stage.md
      - Continuous Elevators:
        - mechanism-examples/elevator/continuous/index.md
        - External Cable Driven Elevator: mechanism-examples/elevator/continuous/examples/cable.md
        - Internal Belt Driven Elevator: mechanism-examples/elevator/continuous/examples/belt.md
      - Shooters:
        - mechanism-examples/shooter/index.md
        - Andrew's Hyper-Hive Shooter: mechanism-examples/shooter/examples/small.md
        - 1678 Citrus Shooter 2022: mechanism-examples/shooter/examples/citrus.md
      - Drivebases:
        - mechanism-examples/drivebase/index.md
        - 2910 Drivebase: mechanism-examples/drivebase/examples/2910.md
        - 972 Brainpan Drivebase: mechanism-examples/drivebase/examples/brainpan.md
    
    - CAD Resources:
      - Featurescripts : resources/featurescripts.md
      - Simplified Models: resources/simplified.md
      - Configurables: resources/configurables.md
      - KrayonCAD: resources/krayonCAD.md
 

  - Contributor's Guide:
    - Style Guide: contribution/styleguide.md
    - Methods of Contributing: contribution/methodsOfContributing.md
    - Contributors: contribution/contributors.md
  

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra_css: [stylesheets/extra.css]

watch:
  - includes

plugins:
  - glightbox:
      background: none
      width: 90%
      shadow: true
  - search